# fly.toml app configuration file generated for hello-world-icy-haze-8056 on 2025-01-12T18:57:51-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-world-icy-haze-8056'
primary_region = 'sea'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  DATABASE_URL = 'sqlite3:///data/production.sqlite3'
  PORT = '8080'

[processes]
  app = './bin/rails server'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
